# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-Y38zGuefmLhUo6_CDEjvMrcdq4ztDU
"""

from hcsr04 import HCSR04
import machine
from machine import Pin
from time import sleep

# LED pin (connected to GPIO 26 on ESP32)
led = Pin(26, Pin.OUT)

# Initialize ultrasonic sensor (HC-SR04)
sensor = HCSR04(trigger_pin=12, echo_pin=14, echo_timeout_us=10000)

while True:
    # Measure distance
    distance = sensor.distance_cm()
    print('Distance:', distance, 'cm')

    # If object is closer than 50 cm, turn LED ON
    if distance < 50:
        led.on()
    else:
        led.off()

    sleep(1)