# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-Y38zGuefmLhUo6_CDEjvMrcdq4ztDU
"""

from hcsr04 import HCSR04
from machine import Pin
from time import sleep

# LED pin (GPIO 26 on ESP32)
led = Pin(26, Pin.OUT)

# Initialize ultrasonic sensor (HC-SR04)
sensor = HCSR04(trigger_pin=21, echo_pin=22, echo_timeout_us=10000)

while True:
    distance = sensor.distance_cm()
    print("Distance:", distance, "cm")

    if distance > 0 and distance < 50:  # Object closer than 50 cm
        led.on()
    else:
        led.off()

    sleep(1)