# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXzOIp8iZnd-B_Eln-3tH7U507vnVd47
"""

import machine
from machine import Pin, SoftI2C
from i2c_lcd import I2cLcd
from time import sleep

# I2C LCD Configuration
I2C_ADDR = 0x27   # Change if needed (use i2c.scan())
ROWS = 2
COLS = 16

# Initialize I2C
i2c = SoftI2C(scl=Pin(22), sda=Pin(21), freq=100000)

# Initialize LCD
lcd = I2cLcd(i2c, I2C_ADDR, ROWS, COLS)

# Initialize LED (GPIO2 = onboard LED for ESP32)
led = Pin(2, Pin.OUT)

# --- Show "HELLO" ---
lcd.clear()
lcd.move_to(4, 0)       # Centered on first row
lcd.putstr("HELLO")
led.on()
sleep(2)
led.off()

# --- Count 1 to 10 ---
for count in range(1, 11):
    lcd.clear()
    lcd.move_to(0, 0)
    lcd.putstr("Counting...")
    lcd.move_to(0, 1)
    lcd.putstr(str(count))   # Print number only
    led.value(count % 2)     # LED ON for odd, OFF for even
    sleep(1)

# --- Final message ---
lcd.clear()
lcd.putstr("Done Counting!")
led.off()